# ** RETO (opcional): Implementación algoritmo de descenso de gradiente en problema con múltiples minínimos locales **
**Facultad de ingeniería, departamento de Ingeniería Biomédica, Universidad de los Andes**\
**IBIO-2440 Programación científica**

**Nombres de los integrantes**


1.   Eliana Saavedra
2.   Santiago Vela

**Número del grupo**

*7*

Considere el problema de optimización:



> $\min_x f(x)$ sujeto a $x\in\mathbb{R}^3$

donde $f:\mathbb{R^3}→\mathbb{R}$ y $x=[x_1,x_2,x_3]^T$. Note que este es un problema de minmización sin restricciones en $\mathbb{R}^3$. Se sabe que la función es derivable y posee varios minimizadores locales entre los cuales hayun minimizador global, todos con posiciones desconocidas. El objetivo del presente laboratorio bono es implementar y utilizar el algoritmo de descenso de gradiente para identificar la mayor cantidad de candidatos a minimizadores locales dentro de una región dada e identificar el posible minimizador global. 

*   Implemente su propia rutina del algoritmo de descenso de gradiente teniendo en cuenta que los minimizadores de la función están definida por $x_i ∈ [-5, 5]$ para cada $i = 1, …, 3$. Es decir, cada componente de $x$ està entre $-5$ y $5$. Defina un tamaño del salto $\alpha$ y un parámetro de criterio de parada $ϵ$ que usted considere conveniente para resolver el problema. Estime el gradiente de la función evaluado en un punto de forma numérica (como se hizo en una práctica anterior), y bajo ninguna circunstancia utilice variables simbólicas.
   
*    Corra el algoritmo de descenso de gradiente al menos para 500 condiciones iniciales diferentes, y guarde las soluciones resultantes de cada corrida (ya sea definidas de forma aleatoria o haciendo un recorrido definido en la región donde se sabe están los minimizadores locales). Basados en estos resultados, realice una tabla donde incluya los valores aproximados de los candidatos a minimizadores locales (recuerden que cada candidato es un vector 3-dimensional), el candidato a minimizador global, y el respectivo número de iteraciones que el algoritmo de descenso de gradiente requirió para llegar a la respuesta.

\\

Esta actividad funciona como un bono para la nota del primer parcial de los integrantes del grupo. La nota se asignará dependiendo de el correcto seguimiento de las instrucciones anteriores y la cantidad de minimizadores locales reales que su algoritmo encuentre. Cada grupo debe desarrollar su propia solución y no se permitirá copia entre grupos de todo el curso. Una falta ante esto se reportará inmediatamente ante el comité de ética de la facultad. 



In [31]:
#@title Corra esta celda para cargar los datos del ejercicio
!pip install benchmark_functions

import benchmark_functions as bf
import numpy as np

# func es el objeto creado con la funcion a minimizar
func = bf.StyblinskiTang(n_dimensions=3)

# grad_finite_diff es una función que calcula el gradiente de una función mediante el método de diferencia finita.
def grad_finite_diff(f, x, h=0.0001):
    """
    Calcula el gradiente de la función f en el punto x mediante el método de diferencia finita.
    """
    grad = np.zeros_like(x)
    for i in range(len(x)):
        x_plus_h = x.copy()
        x_plus_h[i] += h
        grad[i] = (f(x_plus_h) - f(x)) / h
    return grad

# gradient_descent es una función que implementa el algoritmo de descenso de gradiente para minimizar una función f con gradiente gradiente_desc.
def gradient_descent(f, gradiente_desc, alpha=0.01, epsilon=1e-6, x0=None):
    """
    Algoritmo de descenso de gradiente para minimizar la función f con gradiente gradiente_desc.
    """
    if x0 is None:
        # Si no se especifica un punto de inicio, elegimos uno aleatorio 
        x0 = np.random.uniform(-5, 5, size=3)
    x = x0.copy()
    fx = f(x)
    n_iterations = 0
    while True:
        n_iterations += 1
        gradiente = gradiente_desc(f, x)
        x_new = x - alpha * gradiente
        fx_nueva = f(x_new)
        if abs(fx_nueva - fx) < epsilon:
            break
        x = x_new
        fx = fx_nueva
    return x, fx, n_iterations

# Correr el algoritmo para 500 condiciones iniciales diferentes
n_runs = 500
candidates = []
for i in range(n_runs):
    x0 = np.random.uniform(-5, 5, size=3)
    x_min, f_min, n_iterations = gradient_descent(func, grad_finite_diff, x0=x0)
    candidates.append((x_min, f_min, n_iterations))

# Encontrar el candidato a minimizador global
global_min = min(candidates, key=lambda x: x[1])

# Imprimir los resultados en una tabla
print("Candidatos a minimizadores locales:")
print("x\t\t\tf(x)\t\t\tIteraciones")
for candidate in candidates:
    print(f"{candidate[0]}\t{candidate[1]:.6f}\t{candidate[2]}")
print("Candidato a minimizador global:")
print(f"{global_min[0]}\t{global_min[1]:.6f}\t{global_min[2]}")


Candidatos a minimizadores locales:
x			f(x)			Iteraciones
[-2.90358403 -2.90358403  2.7464174 ]	-103.361776	54
[-2.90363135 -2.9035614   2.74702682]	-103.361777	23
[-2.9035858   2.74648445  2.74675435]	-89.225057	30
[-2.90323905 -2.90358086 -2.9035898 ]	-117.498496	28
[ 2.74701485 -2.9034033  -2.90362984]	-103.361777	23
[-2.903252   -2.90358402  2.74675244]	-103.361777	43
[ 2.747124   -2.90364879  2.74681774]	-89.225057	22
[-2.90377907 -2.90358968 -2.90371526]	-117.498495	19
[-2.903584    2.746717    2.74643903]	-89.225057	45
[ 2.7470826  -2.90361414 -2.903652  ]	-103.361777	22
[ 2.74685536 -2.90334359  2.74688698]	-89.225058	25
[-2.90364075  2.74710756 -2.90365082]	-103.361776	22
[-2.90323395  2.74676699 -2.9035774 ]	-103.361776	31
[ 2.74649372  2.74673545 -2.90358379]	-89.225058	35
[ 2.74678758 -2.90328385 -2.9033981 ]	-103.361777	29
[-2.90326541  2.74675849 -2.90348549]	-103.361777	33
[ 2.74644803 -2.90359621 -2.90358112]	-103.361776	25
[-2.90356199 -2.90356967 -2.90332382]	-117.49